create or replace function public.current_kingdom_session_id()
returns uuid
language sql
stable
set search_path = ''
as $$
  select id
  from public.sessions
  where slug = 'kingdom-principles-live'
  limit 1
$$;

revoke all on function public.current_kingdom_session_id() from public;
grant execute on function public.current_kingdom_session_id() to anon, authenticated;

alter table public.sync_state
  add column if not exists id bigint generated by default as identity;

update public.sync_state
set id = 1
where session_id = public.current_kingdom_session_id();

alter table public.sync_state drop constraint if exists sync_state_pkey;
alter table public.sync_state add constraint sync_state_pkey primary key (id);
alter table public.sync_state add constraint sync_state_session_id_key unique (session_id);
alter table public.sync_state alter column session_id set default public.current_kingdom_session_id();

grant insert, update on public.sync_state to anon, authenticated;
grant usage, select on sequence public.sync_state_id_seq to anon, authenticated;

create policy sync_state_public_insert
on public.sync_state
for insert
to anon, authenticated
with check (id = 1 and session_id = public.current_kingdom_session_id());

create policy sync_state_public_update
on public.sync_state
for update
to anon, authenticated
using (id = 1 and session_id = public.current_kingdom_session_id())
with check (id = 1 and session_id = public.current_kingdom_session_id());